### ISSUE TITLE
Missing newline for nested Rule coming after Declaration

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/format-css#1]
Original CSS ([from spec](https://www.w3.org/TR/css-nesting-1/#motivation))

```css
table.colortable {
  & td {
    text-align:center;
    &.c { text-transform:uppercase }
    &:first-child, &:first-child + td { border:1px solid black }
  }
  & th {
    text-align:center;
    background:black;
    color:white;
  }
}
```

Actual outcome

```css
table.colortable {
        & td {
                text-align: center;
                &.c {
                        text-transform: uppercase;
                }

                &:first-child,
                &:first-child + td {
                        border: 1px solid black;
                }
        }

        & th {
                text-align: center;
                background: black;
                color: white;
        }
}
```

Expected outcome

```css
table.colortable {
        & td {
                text-align: center;

                &.c {
                        text-transform: uppercase;
                }

                &:first-child,
                &:first-child + td {
                        border: 1px solid black;
                }
        }

        & th {
                text-align: center;
                background: black;
                color: white;
        }
}
```

[reproduction](https://stackblitz.com/edit/stackblitz-starters-uhsaya?file=index.js)
