### ISSUE TITLE
CSS nesting issues

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/format-css#20]
From nerdy.dev:

```css
@layer base.normalize {
	html {
		--nav-height: 72px;
		view-timeline: document-timeline;

		&:has(.PostList .PostItem:focus-visible) {
			scroll-padding-block-start: calc(var(--nav-height) + var(--size-5));
			scroll-snap-type: y mandatory;

			@media (min-width: 1024px) {
				scroll-padding-block-start: calc(var(--nav-height) + var(--size-9));
			}
		}
	}

	body {
		display: grid;
		grid-template-rows: auto 1fr;
		[data-theme=dark] &:has(.PostDetail .note){background:radial-gradient(circle at 35% 50%,rgba(5,88,255,.15),transparent 50%),radial-gradient(circle at 65% 50%,rgba(128,0,74,.15),transparent 50%),radial-gradient(circle at 50% 65%,rgba(74,128,0,.15),transparent 50%);background-attachment:fixed}@media (prefers-color-scheme:light){&:has(.BlogDetail){background-image:linear-gradient(to bottom,#fff 100vh,300vh,var(--surface-2));background-image:linear-gradient(to bottom,#fff 100vb,300vb,var(--surface-2))}}[data-theme=light] &:has(.BlogDetail){background-image:linear-gradient(to bottom,#fff 100vh,300vh,var(--surface-2));background-image:linear-gradient(to bottom,#fff 100vb,300vb,var(--surface-2))}[data-theme=dark] &:has(.BlogDetail){background-image:none}
	}
}
```
