### ISSUE TITLE
Do better at preserving comments

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/format-css#26]
A lot of comments get lost in formatting, but I want them preserved.

**Comment by bartveneman** [comment]
Geez would have been nice to write down some examples

**Comment by bartveneman** [comment]
examples from lenteveld.nl


```css
.spotlight .button {
    --background-color: var(--root-color--primary);
    --border-top-color: var(--root-color--primary);
    --border-right-color: var(--root-color--primary);
    --border-bottom-color: var(--root-color--primary);
    --border-left-color: var(--root-color--primary);
    /*--border-radius: var(--root-border-radius);*/
    /*--border-style: solid;*/
    /*--border-top-width: var(--root-border-width);*/
    /*--border-right-width: var(--root-border-width);*/
    /*--border-bottom-width: var(--root-border-width);*/
    /*--border-left-width: var(--root-border-width);*/
    --color: var(--root-color--white);
    /*--font-weight: var(--root-font-weight--semi-bold);*/
}
```


```css
.spotlight--layout-6 .spotlight__text .link:hover .icon,
    .spotlight--layout-7 .spotlight__text .link:hover .icon {
        /*--fill: currentColor;*/
    }
```

```css
.button-primary {
    --background-color: var(--root-color--primary);
    /*--border-radius: var(--root-border-radius);*/

    --border-top-color: var(--root-color--primary);
    --border-right-color: var(--root-color--primary);
    --border-bottom-color: var(--root-color--primary);
    --border-left-color: var(--root-color--primary);

    --color: var(--root-color--white);
    /*--font-family: inherit;*/
    /*--font-size: var(--root-font-size); !* Reset, use REM *!*/
    /*--font-style: normal;*/
    /*--font-weight: var(--root-font-weight--semi-bold);*/
    /*--line-height: inherit;*/
}

.button-primary .button__body {
    /*--font-size: 0.889em;*/
}

.button-primary.button--small .button__body {
    /*--font-size: 0.833em;*/
}
```
