### ISSUE TITLE
Make sure Vadim's example works

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/format-css#27]
https://twitter.com/pepelsbey_dev/status/1745386700283466182

```css
@​layer what {
  @​container (width > 0) {
    ul:has(:nth-child(1 of li)) {
      @​media (height > 0) {
        &:hover {
          --is: this;
        }
      }
    }
  }
}
```
