### ISSUE TITLE
Nested rule following declaration needs extra newline

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/format-css#33]
## input

```css
/* test */ a { font: 0/0; & b { color: red; } color: green;}
```

## output

```css
a {
        font: 0/0;
        & b {
                color: red;
        }

        color: green;
}
```

## expected

```css
a {
        font: 0/0;

        & b {
                color: red;
        }

        color: green;
}
```
