### ISSUE TITLE
List item spacing not minified

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/format-css#38]
input

```css
a {
  background: linear-gradient(black 0%, green 100%);
}
```

expected

```diff
-a{background:linear-gradient(black 0%, green 100%);}
+a{background:linear-gradient(black 0%,green 100%);}
```
