### ISSUE TITLE
Format multi-line tokens on a single line

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/format-css#4]
Some example I cooked up:

```css
a {
  background: linear-gradient(
    red,
  10% blue,
20% green,100% yellow);
}

a.b
 .c .d
   .e .f {
color: green }
```

## Actual output

```css
a {
	background: linear-gradient(
    red,
  10% blue,
20% green,100% yellow);
}

a.b
 .c .d
   .e .f {
	color: green;
}
```

## Expected output

```css
a {
	background: linear-gradient(red, 10% blue, 20% green,100% yellow);
}

a.b .c .d .e .f {
	color: green;
}
```
