### ISSUE TITLE
formatting of `[popover]:open`is incorrect

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/format-css#45]
## input

```css
@supports selector([popover]:open){[popover]:not(.\:popover-open,dialog[open]){display:revert}[anchor]:is(:open){inset:auto}}@supports selector([popover]:popover-open){[popover]:not(.\:popover-open,dialog[open]){display:revert}[anchor]:is(:popover-open){inset:auto}}
```

## actual

```css
	@supports selector([popover]: open) {
		[popover]:not(.\:popover-open, dialog[open]) {
			display: revert;
		}

		[anchor]:is(:open) {
			inset: auto;
		}
	}

	@supports selector([popover]: popover-open) {
		[popover]:not(.\:popover-open, dialog[open]) {
			display: revert;
		}

		[anchor]:is(:popover-open) {
			inset: auto;
		}
	}
}
```

## expected

```css
@supports selector([popover]:open) {
	[popover]:not(.\:popover-open, dialog[open]) {
		display: revert;
	}

	[anchor]:is(:open) {
		inset: auto;
	}
}

@supports selector([popover]:popover-open) {
	[popover]:not(.\:popover-open, dialog[open]) {
		display: revert;
	}

	[anchor]:is(:popover-open) {
		inset: auto;
	}
}
```
